repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://gitlab.com/pycqa/flake8  # Flake8 is a Python linting library
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.19.4
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
    -   id: mypy

# - repo: local
#     hooks:
#       - id: install-dependencies
#         name: Install Dependencies
#         entry: poetry install # poetry install --no-root : poetry.toml or poetry.lock ma dependencies haru capture vako hunxa tyo kura run garxa
#         language: python
#         always_run: true
#         pass_filenames: false

#       - id: test  # yadi test xaina vanya yo comment garni
#         name: Run tests
#         entry: poetry run pytest  # commit garnu vanda paila test ta garna ni sakinxa so, sabai test file haru run garxa
#         language: python
#         always_run: true
#         pass_filenames: false
