USER : "PRABESH"
password : "Fuse!234"
account : "cla97133.us-east-1"
database : "FUSECLASSROOM"
schema : "FUSECLASSROOMAPPMONGOPROD"
# mongo_server : "mongodb://localhost:27017/"
# mongo_database : "sse_v2"
# prediction_mongo_collection : "label_prediction"
# centroid_mongo_collection : "ssev2_centers"